In [2]:
from pathlib import Path
import os
import shutil

import pandas as pd
from IPython.display import display

In [3]:
INPUT_DIR = "pyramid-forcing-fftv3-prompts128-30s/pyramid-forcing-best10-30s"
OUTPUT_DIR = "data/26Mar25-PyramidForcingView/pyramid-forcing-best10-30s"
DOWNLOAD_ALL_VIDEOS = False
TARGET_VIDEO_NAME = "video_002.mp4"
USE_HF_MIRROR = False

In [4]:
VIDEO_SUFFIXES = (".mp4", ".mov", ".avi", ".mkv", ".webm")
HF_MIRROR_ENDPOINT = "https://hf-mirror.com"
HF_OFFICIAL_ENDPOINT = "https://huggingface.co"
REPO_ID = "kv-compression/Pyramid-Forcing-Experiments"

def resolve_repo_root() -> Path:
    cwd = Path.cwd().resolve()
    for candidate in [cwd, *cwd.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "data").exists():
            return candidate
    raise FileNotFoundError("Could not locate the repository root from the current working directory.")

def resolve_output_dir(output_dir: str) -> Path:
    raw = Path(output_dir)
    return raw if raw.is_absolute() else resolve_repo_root() / raw

def normalize_input_dir(input_dir: str) -> str:
    value = input_dir.strip()
    if not value:
        raise ValueError("INPUT_DIR must not be empty.")
    return value if value.endswith("/") else f"{value}/"

def resolve_hf_endpoint(use_hf_mirror: bool) -> str:
    return os.environ.get(
        "HF_ENDPOINT",
        HF_MIRROR_ENDPOINT if use_hf_mirror else HF_OFFICIAL_ENDPOINT,
    )

In [5]:
def download_hf_videos(
    *,
    input_dir: str,
    output_dir: str,
    download_all_videos: bool,
    target_video_name: str,
    use_hf_mirror: bool,
    repo_id: str = REPO_ID,
) -> pd.DataFrame:
    from huggingface_hub import HfApi, hf_hub_download

    input_prefix = normalize_input_dir(input_dir)
    hf_endpoint = resolve_hf_endpoint(use_hf_mirror)
    output_path = resolve_output_dir(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if download_all_videos:
        api = HfApi(endpoint=hf_endpoint)
        files = api.list_repo_files(repo_id=repo_id, repo_type="dataset")
        target_files = sorted(
            path
            for path in files
            if path.startswith(input_prefix) and Path(path).suffix.lower() in VIDEO_SUFFIXES
        )
        if not target_files:
            raise FileNotFoundError(f"No video files matched dataset group: {input_prefix}")
    else:
        target_files = [f"{input_prefix}{target_video_name}"]

    print(f"will download {len(target_files)} files")

    rows = []
    for repo_path in target_files:
        destination_path = output_path / Path(repo_path).name
        destination_path.parent.mkdir(parents=True, exist_ok=True)

        if destination_path.exists():
            print("hit local file:", destination_path)
            rows.append({
                "repo_path": repo_path,
                "local_path": str(destination_path),
                "status": "local-hit",
            })
            continue

        print("downloading:", repo_path)
        cached_path = Path(
            hf_hub_download(
                repo_id=repo_id,
                repo_type="dataset",
                filename=repo_path,
                endpoint=hf_endpoint,
            )
        )
        shutil.copy2(cached_path, destination_path)

        rows.append({
            "repo_path": repo_path,
            "local_path": str(destination_path),
            "status": "downloaded-copy",
        })

    return pd.DataFrame(rows)

In [16]:
INPUT_DIR = "pyramid-forcing-fftv3-prompts128-30s/pyramid-forcing-best10-30s"
OUTPUT_DIR = "data/26Mar25-PyramidForcingView/pyramid-forcing-30s"
DOWNLOAD_ALL_VIDEOS = False
TARGET_VIDEO_NAME = "video_021.mp4"
USE_HF_MIRROR = False

# huggingface_hub 1.8.0 reads acceleration flags at import time.
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["HF_XET_HIGH_PERFORMANCE"] = "1"

runtime_config = {
    "input_dir": normalize_input_dir(INPUT_DIR),
    "output_dir": str(resolve_output_dir(OUTPUT_DIR)),
    "download_all_videos": DOWNLOAD_ALL_VIDEOS,
    "target_video_name": TARGET_VIDEO_NAME,
    "use_hf_mirror": USE_HF_MIRROR,
    "hf_endpoint": resolve_hf_endpoint(USE_HF_MIRROR),
    "hf_hub_enable_hf_transfer": os.environ["HF_HUB_ENABLE_HF_TRANSFER"],
    "hf_xet_high_performance": os.environ["HF_XET_HIGH_PERFORMANCE"],
}
display(runtime_config)

result_df = download_hf_videos(
    input_dir=INPUT_DIR,
    output_dir=OUTPUT_DIR,
    download_all_videos=DOWNLOAD_ALL_VIDEOS,
    target_video_name=TARGET_VIDEO_NAME,
    use_hf_mirror=USE_HF_MIRROR,
)
display(result_df)
print("done")

{'input_dir': 'pyramid-forcing-fftv3-prompts128-30s/pyramid-forcing-best10-30s/',
 'output_dir': '/home/winbeau/Tools/jupyter-plot/data/26Mar25-PyramidForcingView/pyramid-forcing-30s',
 'download_all_videos': False,
 'target_video_name': 'video_021.mp4',
 'use_hf_mirror': False,
 'hf_endpoint': 'https://huggingface.co',
 'hf_hub_enable_hf_transfer': '1',
 'hf_xet_high_performance': '1'}

will download 1 files
hit local file: /home/winbeau/Tools/jupyter-plot/data/26Mar25-PyramidForcingView/pyramid-forcing-30s/video_021.mp4

,repo_path,local_path,status
0,pyramid-forcing-fftv3-prompts128-30s/pyramid-f...,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,local-hit

done

In [5]:
TARGET_VIDEO_IDS = [0, 2, 4, 5, 6, 14, 21, 23, 28, 29, 30, 32, 34, 36, 41, 46, 47, 48, 50]
TARGET_VIDEO_NAMES = [f"video_{video_id:03d}.mp4" for video_id in TARGET_VIDEO_IDS]

# Keep the acceleration flags explicit so this cell can be rerun independently.
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["HF_XET_HIGH_PERFORMANCE"] = "1"

batch_runtime_config = {
    "input_dir": normalize_input_dir(INPUT_DIR),
    "output_dir": str(resolve_output_dir(OUTPUT_DIR)),
    "target_video_names": TARGET_VIDEO_NAMES,
    "use_hf_mirror": USE_HF_MIRROR,
    "hf_endpoint": resolve_hf_endpoint(USE_HF_MIRROR),
    "hf_hub_enable_hf_transfer": os.environ["HF_HUB_ENABLE_HF_TRANSFER"],
    "hf_xet_high_performance": os.environ["HF_XET_HIGH_PERFORMANCE"],
}
display(batch_runtime_config)

result_frames = []
for target_video_name in TARGET_VIDEO_NAMES:
    result_frames.append(
        download_hf_videos(
            input_dir=INPUT_DIR,
            output_dir=OUTPUT_DIR,
            download_all_videos=False,
            target_video_name=target_video_name,
            use_hf_mirror=USE_HF_MIRROR,
        )
    )

batch_result_df = pd.concat(result_frames, ignore_index=True)
display(batch_result_df)
print("done")

{'input_dir': 'rolling-forcing-60s/',
 'output_dir': '/home/winbeau/Tools/jupyter-plot/data/26Mar25-PyramidForcingView/rolling-forcing-60s',
 'target_video_names': ['video_000.mp4',
  'video_002.mp4',
  'video_004.mp4',
  'video_005.mp4',
  'video_006.mp4',
  'video_014.mp4',
  'video_021.mp4',
  'video_023.mp4',
  'video_028.mp4',
  'video_029.mp4',
  'video_030.mp4',
  'video_032.mp4',
  'video_034.mp4',
  'video_036.mp4',
  'video_041.mp4',
  'video_046.mp4',
  'video_047.mp4',
  'video_048.mp4',
  'video_050.mp4'],
 'use_hf_mirror': True,
 'hf_endpoint': 'https://hf-mirror.com',
 'hf_hub_enable_hf_transfer': '1',
 'hf_xet_high_performance': '1'}

will download 1 files
downloading: rolling-forcing-60s/video_000.mp4

video_000.mp4:   0%|          | 0.00/65.0M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_002.mp4

video_002.mp4:   0%|          | 0.00/59.4M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_004.mp4

video_004.mp4:   0%|          | 0.00/44.2M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_005.mp4

video_005.mp4:   0%|          | 0.00/83.5M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_006.mp4

video_006.mp4:   0%|          | 0.00/62.2M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_014.mp4

video_014.mp4:   0%|          | 0.00/62.2M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_021.mp4

video_021.mp4:   0%|          | 0.00/75.8M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_023.mp4

video_023.mp4:   0%|          | 0.00/68.2M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_028.mp4

video_028.mp4:   0%|          | 0.00/52.9M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_029.mp4

video_029.mp4:   0%|          | 0.00/46.0M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_030.mp4

video_030.mp4:   0%|          | 0.00/43.3M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_032.mp4

video_032.mp4:   0%|          | 0.00/67.4M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_034.mp4

video_034.mp4:   0%|          | 0.00/95.8M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_036.mp4

video_036.mp4:   0%|          | 0.00/73.5M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_041.mp4

video_041.mp4:   0%|          | 0.00/59.6M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_046.mp4

video_046.mp4:   0%|          | 0.00/53.0M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_047.mp4

video_047.mp4:   0%|          | 0.00/56.9M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_048.mp4

video_048.mp4:   0%|          | 0.00/43.6M [00:00<?, ?B/s]

will download 1 files
downloading: rolling-forcing-60s/video_050.mp4

video_050.mp4:   0%|          | 0.00/58.7M [00:00<?, ?B/s]

,repo_path,local_path,status
0,rolling-forcing-60s/video_000.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
1,rolling-forcing-60s/video_002.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
2,rolling-forcing-60s/video_004.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
3,rolling-forcing-60s/video_005.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
4,rolling-forcing-60s/video_006.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
5,rolling-forcing-60s/video_014.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
6,rolling-forcing-60s/video_021.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
7,rolling-forcing-60s/video_023.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
8,rolling-forcing-60s/video_028.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
9,rolling-forcing-60s/video_029.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
10,rolling-forcing-60s/video_030.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
11,rolling-forcing-60s/video_032.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
12,rolling-forcing-60s/video_034.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
13,rolling-forcing-60s/video_036.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
14,rolling-forcing-60s/video_041.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
15,rolling-forcing-60s/video_046.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
16,rolling-forcing-60s/video_047.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
17,rolling-forcing-60s/video_048.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy
18,rolling-forcing-60s/video_050.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,downloaded-copy

done