In [1]:
from pathlib import Path
import sys


def resolve_repo_root() -> Path:
    cwd = Path.cwd().resolve()
    for candidate in [cwd, *cwd.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "data").exists():
            return candidate
    raise FileNotFoundError("Could not locate the repository root from the current working directory.")


NOTEBOOK_DIR = resolve_repo_root() / "notebooks" / "26Mar25-PyramidForcingView"
if str(NOTEBOOK_DIR) not in sys.path:
    sys.path.insert(0, str(NOTEBOOK_DIR))

from opencv_extract_frames import extract_frames

In [14]:
INPUT_DIR = "data/26Mar25-PyramidForcingView/pyramid-forcing-30s"
OUTPUT_DIR = "figures/26Mar25-PyramidForcingView/pyramid-forcing-30s"
FRAME_STRIDE = 16
EXTRACT_ALL_VIDEOS = False
TARGET_VIDEO_NAME = "video_021.mp4"
extract_frames(INPUT_DIR, OUTPUT_DIR, FRAME_STRIDE, EXTRACT_ALL_VIDEOS, TARGET_VIDEO_NAME)

{'input_dir': '/home/winbeau/Tools/jupyter-plot/data/26Mar25-PyramidForcingView/pyramid-forcing-30s',
 'output_dir': '/home/winbeau/Tools/jupyter-plot/figures/26Mar25-PyramidForcingView/pyramid-forcing-30s',
 'frame_stride': 16,
 'extract_all_videos': False,
 'target_video_name': 'video_021.mp4',
 'max_workers': 8}

{'mode': 'single_video',
 'selected_video_count': 1,
 'worker_count': 1,
 'summary_path': '/home/winbeau/Tools/jupyter-plot/figures/26Mar25-PyramidForcingView/pyramid-forcing-30s/frame_export_summary.csv'}

,video_name,normalized_video_id,stage,decoded_frames,saved_frames,sheet_pages,last_output
0,video_021.mp4,pyramid-forcing-30s_video_021,done,489,31,1/1,/home/winbeau/Tools/jupyter-plot/figures/26Mar...

Frames | video_021.mp4:   0%|          | 0/489 [00:00<?, ?frame/s]

Sheets | video_021.mp4:   0%|          | 0/2 [00:00<?, ?sheet/s]

,normalized_video_id,video_name,video_path,decoded_frame_count,exported_frame_count,frame_stride,frame_dir,sheet_count,overview_path,status
0,pyramid-forcing-30s_video_021,video_021.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,489,31,16,/home/winbeau/Tools/jupyter-plot/figures/26Mar...,1,/home/winbeau/Tools/jupyter-plot/figures/26Mar...,ok

Saved frame export summary to /home/winbeau/Tools/jupyter-plot/figures/26Mar25-PyramidForcingView/pyramid-forcing-30s/frame_export_summary.csv

,normalized_video_id,video_name,video_path,decoded_frame_count,exported_frame_count,frame_stride,frame_dir,sheet_count,overview_path,status
0,pyramid-forcing-30s_video_021,video_021.mp4,/home/winbeau/Tools/jupyter-plot/data/26Mar25-...,489,31,16,/home/winbeau/Tools/jupyter-plot/figures/26Mar...,1,/home/winbeau/Tools/jupyter-plot/figures/26Mar...,ok